language: java
os:
  - osx

# don't build for generated release builds
branches:
  except:
    - /^untagged/

env:
  - GRAAL_NATIVE='TRUE'
  - GRAAL_NATIVE='FALSE'

install:
  - wget --output-document=jdk.tar.gz "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java11-darwin-amd64-19.3.1.tar.gz"
  - export JAVA_HOME=$HOME/graal
  - mkdir -p $JAVA_HOME
  - tar --extract --file jdk.tar.gz -C $JAVA_HOME --strip-components=3
  - export PATH=$JAVA_HOME/bin:$PATH
  - gu install native-image

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./build.sh

before_deploy:
  - mkdir -p dist
  - mv jsonsql dist/
  - tar -czf jsonsql.osx.tar.gz -C dist .
  - shasum -a 256 jsonsql.osx.tar.gz

deploy:
  provider: releases
  api_key:
    secure: Z2tdNp/mJAGDMPFSOuyB2NEZmKnXOuNJcXmWFXEDo88XmpTibPatQH2MmgEG7TC9w3Shijwrp2DFAeFvdmCRclJ1kl6rozx4tGffghVBQr7a7HgvKlmWEtvcgw8vPMM86/btNmKiiPNyoBnhu62noMYL2dFm/9jfTgReZNTGofUOl9NZ6RDGVvqPA/YApCrqjNOMT+GEIwwoBqZlGolkrjcZeNcyautCLANTA+XnLMF5h0vVZP2xNhte18lueokqqiKrTMdtuG08HgMbM9MlE72ZzO99Y0bTQBwJVMZWrU8xOM44RFVXcmg4x4GqLRBbIDNH093o22FZ34sEoH67tnrlRoM4EmSv5p3A8L+BzorY6dRpTWcVsHrQeEs+52hwZFjcQ2xgfSSFHjRhQptQMmel4ByhtDqFzC83aogF8GsBB4dK0T9+n4/KhbSlsR0rSh1JUjAEx/w/8KBEHYeGPolY94EeY5RQbzZooECYpxIuWfE2M8PmsRMlRDWcpSbLZLdbnqcrtlvjLr7i5IhlGI19z6eczwPmHaANzt1/hyL1WF8gEwjmBaOjles/Dz2jMf2uhA6CcyIv+Vb3vcYDI4Mg5RgWtIWYeJ2oEmMUtB9d2u1dLC4gySb3Lh4Evgkp19iLKMi4M8r5eOc5DWOfsjUHyQ3KxUDYZ0vIY/h0pSE=
  file:
    - jsonsql.osx.tar.gz
  skip_cleanup: true
  on:
    condition: $GRAAL_NATIVE == 'TRUE'
    repo: tim-patterson/jsonsql
    tags: true
